### ISSUE TITLE
ImportError: No module named importlib

### ISSUE THREAD

**Issue by zh-h** [NetAngels/django-webodt#22]
``` python
Unhandled exception in thread started by <function wrapper at 0x7fe7a2746d70>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/webodt/__init__.py", line 18, in <module>
    from webodt.preprocessors import list_preprocessors
  File "/usr/local/lib/python2.7/dist-packages/webodt/preprocessors.py", line 2, in <module>
    from django.utils.importlib import 
```

It is successfully installed

**Comment by kevwilde** [comment]
This is because Django 1.9 is not supported by webodt at the moment. This is the warning I receive in my Django 1.8 project:

```
RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module
```
